apiVersion: batch/v1
kind: Job
metadata:
  name: test-job 
spec:
  completions: 5 # Número de ejecuciones
  template:
    spec:
      containers:
      - name: test 
        image: busybox
        command: ["/bin/sleep"]
        args: ["3"]
      restartPolicy: Never
